name: version-and-changelog

on:
  workflow_call:

jobs:
  version-and-changelog:
    runs-on: [self-hosted, linux, arm64]  # Or ubuntu-latest if not using the Pi

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate next semantic version
        id: version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"

      - name: Update CHANGELOG.md
        uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: ${{ github.repository }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: 'docs/CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update for v${{ steps.version.outputs.version }}'
          TYPE: 'feat:Features,fix:Bug Fixes,docs:Documentation,refactor:Refactors,perf:Performance Improvements'

      - name: Git tag and push
        run: |
          git config --global user.email "bot@bodegacatsgc.gg"
          git config --global user.name "GitHub Actions Bot"
          git add CHANGELOG.md
          git commit -m "docs(CHANGELOG): update for v${{ steps.version.outputs.version }}"
          git tag v${{ steps.version.outputs.version }}
          git push origin main --tags
